version: '3.4'

services:
  iot.webapicore:
    image: ${DOCKER_REGISTRY-}iotwebapicore
    build:
      context: .
      dockerfile: IoT/IoT.WebApiCore/Dockerfile
networks:
  defauld:
    external:
      name: microservecenet